# Generated by Django 5.2.6 on 2025-10-01 09:59

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_category_options_alter_entry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g., #007bff)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_category_name_per_user', violation_error_message='You already have a category with this name (case-insensitive).'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('mood_rating__gte', 1), ('mood_rating__lte', 10)), name='mood_rating_range', violation_error_message='Mood rating must be between 1 and 10.'),
        ),
    ]
